[colors]
draw_bold_text_with_bright_colors = false 
[env]
TERM = "xterm-256color"

[font]
size = 13

[font.normal]
family = "Jetbrains Mono Nerd Font"
style = "bold"
[font.bold]
family = "victor mono"
style = "bold italic"
[font.italic]
family = "victor mono"	
style = "italic"
[font.bold_italic]
family = "victor mono"	
style = "bold italic"
[selection]
save_to_clipboard = false

[window]
fps = 40
# dynamic_padding = true
# dynamic_title = true
opacity = 0.9

[window.dimensions]
columns = 100
lines = 30

[window.padding]
x = 0
y = 0
[cursor]
# Set to false to disable completely
# smooth_motion = false
# # 0.0 = cursor is not moving, 1.0 = cursor moves instantly
# smooth_motion_factor = 0.2
# # 0.0 = broken, 1.0 = cursor shape is unaffected by movement
# smooth_motion_spring = 1.0
# # Limits how the cursor size may change
# smooth_motion_max_stretch_x = 1.1
# smooth_motion_max_stretch_y = 1.1
# # Override "block" cursor if you don't like how it looks in this fork
# # I prefer "underline"
# block_replace_shape = "block"

[cursor.style]
blinking = "off"
shape = "Block"

[general]
live_config_reload =false
import = ["~/.config/alacritty/color.toml"]
shader = "shaders/fire.glsl"
# shader = "shaders/star.glsl"
# [features]
# default = ["wayland"]
[keyboard]
bindings = [
{ key = "Enter", mods = "Shift", action = "CreateNewWindow" },
{ key = "L", mods = "Control|Shift", chars = "l" },
]
[scrollbar]
mode = "Fading"


   
