[colors]
draw_bold_text_with_bright_colors = false 
[env]
TERM = "xterm-256color"

[font]
size = 13

[font.normal]
family = "Jetbrains Mono"
style = "bold"
[font.bold]
family = "victor mono"
style = "bold italic"
[font.italic]
family = "victor mono"	
style = "italic"
[font.bold_italic]
family = "victor mono"	
style = "bold italic"
[selection]
save_to_clipboard = false

[window]
# dynamic_padding = true
# dynamic_title = true
opacity = 0.9

[window.dimensions]
columns = 100
lines = 40

[window.padding]
x = 0
y = 0
[cursor]
blink_interval = 200
unfocused_hollow = true
smooth_motion_max_stretch_y = 8.0
vi_mode_style = "Block"
smooth_motion_spring = 0.8

[cursor.style]
blinking = "off"
shape = "Block"

[general]
live_config_reload =false
import = ["~/.config/alacritty/color.toml"]
# [features]
# default = ["wayland"]
[keyboard]
bindings = [
{ key = "Enter", mods = "Shift", action = "CreateNewWindow" },
{ key = "L", mods = "Control|Shift", chars = "l" },
]


   
